# Generated by Django 2.1.7 on 2021-11-29 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211129_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 29, 15, 15, 43, 444768)),
        ),
    ]
